#
# $Id: Makefile.usrdef 3 2013-05-20 13:07:23Z cota@upard.org $
# Copyright (c) 2016 Cota Nabeshima <cota@upard.org>
# This file is subject to the MIT license available at,
# http://opensource.org/licenses/mit-license.php
#

INSTALLPATH=/usr/local

CXX=g++

CFLAGS_TEST=-Wall -g -I../../ -I/usr/include/c++/4.2.1 -stdlib=libstdc++ # -D_SIGEXCEPTION_ Exception.cpp 
LDFLAGS_TEST=-stdlib=libstdc++
