#
# $Id$
# Copyright (c) 2013 Cota Nabeshima <cota@upard.org>
# This file is subject to the MIT license available at,
# http://opensource.org/licenses/mit-license.php
#

all:
qmake:
install:

doc:
	doxygen

distclean: clean
	rm -rf *~ html latex

clean:
	rm -rf *~
