#
# $Id$
# Copyright (c) 2016 Cota Nabeshima <cota@upard.org>
# This file is subject to the MIT license available at,
# http://opensource.org/licenses/mit-license.php
#

all:

doc:
	doxygen

distclean clean:
	rm -rf *~ html latex
