#
# $Id: Makefile 3 2013-05-20 13:07:23Z cota@upard.org $
# Copyright (c) 2016 Cota Nabeshima <cota@upard.org>
# This file is subject to the MIT license available at,
# http://opensource.org/licenses/mit-license.php
#

all:
qmake:
install:

doc:
	doxygen

distclean: clean
	rm -rf *~ html latex

clean:
	rm -rf *~
