#
# $Id: Makefile 4 2013-09-11 05:53:28Z cota@upard.org $
# Copyright (c) 2016 Cota Nabeshima <cota@upard.org>
# This file is subject to the MIT license available at,
# http://opensource.org/licenses/mit-license.php
#

all:
qmake:
install:

doc:
	doxygen

distclean: clean
	rm -rf *~ html latex

clean:
	rm -rf *~
